export const UPDATE_RATE = "UPDATE_RATE";
export const SUBSCRIBE_TO_RATE = "SUBSCRIBE_TO_RATE";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const SORT_TRANSACTIONS = "SORT_TRANSACTIONS";
export const APPLY_FILTER = "APPLY_FILTER";